name: api-rest-nodejs

runtime: nodejs

vars:
  stages:
    local:
      mongodb: 
        uri: mongodb://localhost/myapp
        options:
          useMongoClient: true
      response-http-headers:
        - Access-Control-Allow-Origin: "*"
        - Access-Control-Allow-Headers: "Authorization, Content-Type"
    dev:
      mongodb:
        uri: ${env.mongo_uri}
        options:
          useMongoClient: true        
      response-http-headers:
        - Access-Control-Allow-Origin: "*"
        - Access-Control-Allow-Headers: "Authorization, Content-Type"
    prod:
      mongodb: 
        uri: ${env.mongo_uri}
        options:
          useMongoClient: true        
      response-http-headers:
        - Access-Control-Allow-Origin: "http://example.org"

plugins:
  - squeezer-serve
  - squeezer-swagger

swagger: !!inc/file "swagger.yml"