info:
  title: API Documentation
  description: Detailed documentation for available API endpoints
definitions:
  ErrorResponseV1:
    type: object
    properties:
      errors:
        type: object
      message:
        type: string
        default: error message
  ProductV1:
    type: object
    required:
      - title
      - category
      - price
      - stock
    properties:
      title:
        type: string
      category:
        type: string
      price:
        type: integer
      stock:
        type: integer        