info:
  title: API Documentation
  description: Detailed documentation for available API endpoints
definitions:
  GetResponseV1:
    type: object
    properties:
      message:
        type: string
        default: success
      statusCode:
        type: integer
        default: 200
  ErrorResponseV1:
    type: object
    properties:
      message:
        type: string
        default: error message
      code:
        type: string
        default: error code
      statusCode:
        type: integer
        default: 400
  ProductV1:
    type: object
    required:
      - title
      - category
      - price
      - stock
    properties:
      title:
        type: string
      category:
        type: string
      price:
        type: integer
      stock:
        type: integer        