paths:
  /rest/v1/hello:
    get:
      summary: Says hello
      description: Says hello
      tags:
        - Hello
      produces:
        - application/json
#      parameters:
#        - in: body
#          name: body
#          description: Product object that needs to be added to the store
#          required: true
#          schema:
#            $ref: '#/definitions/Product'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/GetResponse'
        400:
          description: bad request
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: internal error
definitions:
  GetResponse:
    type: object
    properties:
      message:
        type: string
        default: success
      data:
        type: object
        $ref: '#/definitions/Hello'
      statusCode:
        type: integer
        default: 200
  RemoveResponse:
    type: object
    properties:
      message:
        type: string
        default: success
      statusCode:
        type: integer
        default: 200
  ErrorResponse:
    type: object
    properties:
      message:
        type: string
        default: error message
      code:
        type: string
        default: error code
      statusCode:
        type: integer
        default: 400
  Hello:
    type: object
    required:
      - text
      - event
      - price
    properties:
      text:
        type: string
      event:
        type: object
