AWSTemplateFormatVersion: "2010-09-09"
Description: CDN Stack
Parameters:
  SqueezerDeploymentBucketDomain:
    Type: "String"
Resources:
  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName:
              Ref: SqueezerDeploymentBucketDomain
            Id: SqueezerDeploymentBucketDomain
            S3OriginConfig:
              OriginAccessIdentity: ""
        Enabled: true
#        Aliases:
#          - foo.bar
#          - www.foo.bar
        DefaultCacheBehavior:
          TargetOriginId: SqueezerDeploymentBucketDomain
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_100
Outputs:
  CloudFrontDomain:
    Value:
      Fn::GetAtt:
      - CDN
      - DomainName
