name: api-rest

runtime: nodejs

vars:
  stages:
    local:
      response-http-headers:
        - Access-Control-Allow-Origin: "*"
        - Access-Control-Allow-Headers: "Authorization, Content-Type"
    dev:
      response-http-headers:
        - Access-Control-Allow-Origin: "*"
        - Access-Control-Allow-Headers: "Authorization, Content-Type"
    prod:
      response-http-headers:
        - Access-Control-Allow-Origin: "http://example.org"

plugins:
  - squeezer-serve
  - squeezer-swagger

swagger: !!inc/file "swagger.yml"