paths:
  /rest/v1/products:
    post:
      summary: Add a product
      description: Add a product as a JSON object
      tags:
        - Products
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Product object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/GetResponse'
        400:
          description: bad request
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: internal error
    get:
      summary: List all products
      description: List all products as an JSON array
      tags:
        - Products
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/ListResponse'
        400:
          description: bad request
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: internal error
  /rest/v1/products/{id}:
    get:
      summary: Get a product
      description: Get a product
      tags:
        - Products
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: product id
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/GetResponse'
        400:
          description: bad request
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: internal error
    delete:
      summary: Removes a product
      description: Removes a product
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: product id
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/RemoveResponse'
        400:
          description: bad request
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: internal error
    put:
      summary: Update a product
      description: Update a product
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: product id
          required: true
          type: string
        - in: body
          name: body
          description: Product object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Product'
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/GetResponse'
        400:
          description: bad request
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: internal error
definitions:
  ListResponse:
    type: object
    properties:
      message:
        type: string
        default: success
      data:
        type: array
        items:
          $ref: '#/definitions/Product'
      statusCode:
        type: integer
        default: 200
  GetResponse:
    type: object
    properties:
      message:
        type: string
        default: success
      data:
        type: object
        $ref: '#/definitions/Product'
      statusCode:
        type: integer
        default: 200
  RemoveResponse:
    type: object
    properties:
      message:
        type: string
        default: success
      statusCode:
        type: integer
        default: 200
  ErrorResponse:
    type: object
    properties:
      message:
        type: string
        default: error message
      code:
        type: string
        default: error code
      statusCode:
        type: integer
        default: 400
  Product:
    type: object
    required:
      - title
      - category
      - price
    properties:
      title:
        type: string
      category:
        type: string
      price:
        type: integer
