AWSTemplateFormatVersion: "2010-09-09"
Description: Dynamo Stack
#Parameters:
Resources:
  ProductsDynamo:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${vars.env.PRODUCTS_TABLE_READ_CAPACITY}
        WriteCapacityUnits: ${vars.env.PRODUCTS_TABLE_WRITE_CAPACITY}
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
Outputs:
  ProductsDynamoTable:
    Value:
      Ref: ProductsDynamo
  ProductsDynamoTableStreamArn:
    Value:
      Fn::GetAtt:
        - ProductsDynamo
        - StreamArn
