AWSTemplateFormatVersion: "2010-09-09"
Description: SNS Stack
Resources:
  mySNSTopic:
    Type: "AWS::SNS::Topic"
Outputs:
  mySNSTopicName:
    Value:
      Fn::GetAtt:
        - mySNSTopic
        - TopicName
  mySNSTopicNameArn:
    Value:
      Ref: mySNSTopic
