# SQUEEZER MICROSERVICE

name: hello
description: Hello !!!!!

# ENVIRONMENT VARIABLES ( accessible via "process.env" in NodeJS )
env:
#  MSG: hello
  dev:
#    MSG: hello dev
  prod:
#    MSG: hello prod

functions:
  hello:
#     Function description
#     http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-description
    description: Says hello

#     Handler
#     http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html
    handler: hello

#     Memory size ( MB )
#     https://aws.amazon.com/lambda/pricing/
    memory: 128

#     Execution timeout
#     http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-timeout
    timeout: 6

#     invoke current lambda function when some of the next events is triggered
#     http://docs.aws.amazon.com/lambda/latest/dg/invoking-lambda-function.html
    events:
      - http:
          path: /
          method: get

# INCLUDES FILES OR DIRECTORIES FROM PROJECT ( should appear on "src/inclusions/DEST" microservice's path )
inclusions:
  - src: lib/http
    dest: http
  - src: web/templates
    dest: templates

packaging:
  - node_modules
  - inclusions/http
  - inclusions/templates
#  - other_dir
#  - other_file
